Change DictConfig MutableMapping parameter to Any.
	modified:   omegaconf/dictconfig.py

Changing the declaration of DictConfig from
    class DictConfig(BaseContainer, MutableMapping[DictKeyType, Any]):
to
    class DictConfig(BaseContainer, MutableMapping[Any, Any]):

This eliminates some mypy errors.

For example, the following code was giving mypy errors when using the
old declaration:

    from omegaconf import OmegaConf
    cfg = OmegaConf.create()
    upd = dict(a=1)
    cfg.update(upd)

The mypy error was:

    error: Argument 1 to "update" of "MutableMapping" has incompatible type "Dict[str, int]"; expected "Mapping[Union[str, int, Enum], Any]"

An alternative to using `MutableMapping[Any, Any]` would have been
something like
```
KT = TypeVar("KT", bound=DictKeyType)
class DictConfig(BaseContainer, MutableMapping[KT, Any]): ...
```
but this alternative would have introduced additional complexity, such
as requiring parametrization of DictConfig instances, e.g.
`DictConfig[int]` or `DictConfig[str]`.